
["Herb Jar Settings"]
	#Disabling allows jars to hold any item
	jars_only_hold_herbs = true

["Sage Burning Plate Settings"]
	#Range of the Sage Burning Plate, setting to 0 will disable completely
	spawn_disable_range = 48

["Crow Pickpocket Cooldown"]
	#time (in ticks) for crow being able to pickpocket again (base 1 minute 30 seconds)
	crow_pickpocket_cooldown = 1800

["Coffer Item Blacklist"]
	#blacklists items from being placed inside of coffers
	coffer_blacklist = ["minecraft:shulker_box", "minecraft:white_shulker_box", "minecraft:orange_shulker_box", "minecraft:magenta_shulker_box", "minecraft:light_blue_shulker_box", "minecraft:yellow_shulker_box", "minecraft:lime_shulker_box", "minecraft:pink_shulker_box", "minecraft:gray_shulker_box", "minecraft:light_gray_shulker_box", "minecraft:cyan_shulker_box", "minecraft:purple_shulker_box", "minecraft:blue_shulker_box", "minecraft:brown_shulker_box", "minecraft:green_shulker_box", "minecraft:red_shulker_box", "minecraft:black_shulker_box", "hexerei:coffer"]

["Biome Generation"]
	#rarity of the willow swamp biome, 0 to disable
	#Range: > 0
	willow_swamp_rarity = 2

